<a href="https://colab.research.google.com/github/Aliweb789/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Student_Performance.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print("First few rows of the dataset:")
print(df.head())

print("Summary statistics:")
print(df.describe())

print("Data types of columns:")
print(df.info())

Dataset shape (rows, columns): (25000, 16)
Column name: ['student_id', 'age', 'gender', 'school_type', 'parent_education', 'study_hours', 'attendance_percentage', 'internet_access', 'travel_time', 'extra_activities', 'study_method', 'math_score', 'science_score', 'english_score', 'overall_score', 'final_grade']
First few rows of the dataset:
   student_id  age  gender school_type parent_education  study_hours  \
0           1   14    male      public    post graduate          3.1
1           2   18  female      public         graduate          3.7
2           3   17  female     private    post graduate          7.9
3           4   16   other      public      high school          1.1
4           5   16  female      public      high school          1.3

   attendance_percentage internet_access travel_time extra_activities  \
0                   84.3             yes     <15 min              yes
1                   87.8             yes     >60 min               no
2                   65.5              no     <15 min               no
3                   58.1              no   15-30 min               no
4                   61.0             yes   30-60 min              yes

  study_method  math_score  science_score  english_score  overall_score  \
0        notes        42.7           55.4           57.0           53.1
1     textbook        57.6           68.8           64.8           61.3
2        notes        84.8           95.0           79.2           89.6
3        notes        44.4           27.5           54.7           41.6
4  group study         8.9           32.7           30.0           25.4

  final_grade
0           e
1           d
2           b
3           e
4           f
Summary statistics:
        student_id           age   study_hours  attendance_percentage  \
count  25000.00000  25000.000000  25000.000000           25000.000000
mean    7493.04380     16.482760      4.253224              75.084084
std     4323.56215      1.703895      2.167541              14.373171
min        1.00000     14.000000      0.500000              50.000000
25%     3743.75000     15.000000      2.400000              62.800000
50%     7461.50000     16.000000      4.300000              75.100000
75%    11252.00000     18.000000      6.100000              87.500000
max    15000.00000     19.000000      8.000000             100.000000

         math_score  science_score  english_score  overall_score
count  25000.000000   25000.000000   25000.000000   25000.000000
mean      63.785944      63.745320      63.681948      64.006172
std       20.875262      20.970529      20.792693      18.932025
min        0.000000       0.000000       0.000000      14.500000
25%       48.300000      48.200000      48.300000      49.000000
50%       64.100000      64.100000      64.200000      64.200000
75%       80.000000      80.000000      80.000000      79.000000
max      100.000000     100.000000     100.000000     100.000000
Data types of columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             25000 non-null  int64
 1   age                    25000 non-null  int64
 2   gender                 25000 non-null  object
 3   school_type            25000 non-null  object
 4   parent_education       25000 non-null  object
 5   study_hours            25000 non-null  float64
 6   attendance_percentage  25000 non-null  float64
 7   internet_access        25000 non-null  object
 8   travel_time            25000 non-null  object
 9   extra_activities       25000 non-null  object
 10  study_method           25000 non-null  object
 11  math_score             25000 non-null  float64
 12  science_score          25000 non-null  float64
 13  english_score          25000 non-null  float64
 14  overall_score          25000 non-null  float64
 15  final_grade            25000 non-null  object
dtypes: float64(6), int64(2), object(8)
memory usage: 3.1+ MB
None

In [ ]:
print("Average score by columns:")
df[["math_score", "english_score", "science_score"]].mean()

Average score by columns:

math_score       63.785944
english_score    63.681948
science_score    63.745320
dtype: float64

In [ ]:
print("Maximum score by subject:")
df[["math_score", "english_score", "science_score"]].max()

Maximum score by subject:

math_score       100.0
english_score    100.0
science_score    100.0
dtype: float64

In [ ]:
print("Minimum score by columns:")
df[["math_score", "english_score", "science_score"]].min()

Minimum score by columns:

math_score       0.0
english_score    0.0
science_score    0.0
dtype: float64

In [ ]:
# Correlation
print("Correlation:")
df[["math_score", "english_score", "science_score"]].corr()

Correlation:

               math_score  english_score  science_score
math_score       1.000000       0.786315       0.784111
english_score    0.786315       1.000000       0.783951
science_score    0.784111       0.783951       1.000000

In [ ]:
df["total score"] = df[["math_score", "english_score", "science_score"]].sum(axis=1)
df["average score:"] = df["total score"] / 3
df["passed"] = np.where(df["average score:"] >= 50, "Pass", "Fail")

print("New coulmns preview (total, average, passed):")
print(df[["total score", "average score:", "passed"]].head())

New coulmns preview (total, average, passed):
   total score  average score: passed
0        155.1       51.700000   Pass
1        191.2       63.733333   Pass
2        259.0       86.333333   Pass
3        126.6       42.200000   Fail
4         71.6       23.866667   Fail

In [ ]:
test_prep_group = df.groupby("study_method")[["math_score", "english_score", "science_score"]].mean()
print("Students score by test preparation course:")
print(test_prep_group)

# Gender-based average
gender_group = df.groupby("gender")[["math_score", "english_score", "science_score"]].mean()
print("Average score by gender:")
print(gender_group)

# Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:")
print(pass_rate)

Students score by test preparation course:
               math_score  english_score  science_score
study_method
coaching        64.207129      64.082787      64.064382
group study     62.968264      62.977359      63.091369
mixed           63.524787      63.394218      63.204031
notes           64.011525      63.719760      63.437695
online videos   64.106910      64.341967      64.313771
textbook        63.907266      63.594126      64.374782
Average score by gender:
        math_score  english_score  science_score
gender
female   64.045428      63.893317      63.965862
male     63.872754      63.661150      63.852104
other    63.447170      63.495167      63.425227
Pass rate:
passed
Pass    73.492
Fail    26.508
Name: proportion, dtype: float64

In [ ]:
# Convert score to NumPy array
scores = df[["math_score", "english_score", "science_score"]].values

# Mean, Std Deviation
print("NumPy Mean:", np.mean(scores, axis=0))
print("NumPy Std:", np.std(scores, axis=0))

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores (normalized numbers)")
print(z_score[:5])
# Average 0
# Negative -
# Positive +

NumPy Mean: [63.785944 63.681948 63.74532 ]
NumPy Std: [20.87484433 20.79227728 20.97010986]
Z-scores (normalized numbers)
[[-1.01011263 -0.32136682 -0.39796263]
 [-0.29633486  0.05377246  0.24104213]
 [ 1.00666887  0.7463373   1.4904395 ]
 [-0.9286749  -0.43198481 -1.72842776]
 [-2.62928639 -1.61992588 -1.48045576]]

In [ ]:
# How many students scored above 90 average?
top_scores = df[df["average score:"] >= 90]
print("Top scored students above 90:", len(top_scores))

# How many failed?
failed = df[df["passed"] == "Fail"]
print("Failed students:", len(failed))

Top scored students above 90: 2407
Failed students: 6627